#!/bin/bash

EXEDIR=$(dirname ${BASH_SOURCE[0]})
me=$0
justme=$(basename $me)

source /etc/profile.d/modules.sh 2>/dev/null
ml purge
ml ncarenv python
ncar_pylib > /dev/null
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

helpstr=""
for arg in $@
do
   if [[ "$arg" = "--help" ]] || [[ "$arg" = "-h" ]]; then
      helpstr="help"
   fi
done
if [ -z "$helpstr" ] ; then
   $EXEDIR/$justme.py $*
else
   $EXEDIR/$justme.py $* | sed -e 's/qdh.py/qdh/g'
fi
