#!/bin/bash

EXEDIR=$(dirname ${BASH_SOURCE[0]})
echo $EXEDIR
me=$0
justme=$(basename $me)

source /etc/profile.d/modules.sh 2>/dev/null
ml purge
ml ncarenv python
ncar_pylib > /dev/null
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

$EXEDIR $justme.py $*
