#!/bin/bash

host=$(hostname)
if [ ! $(hostname|grep casper) ] ; then
   echo 'Please execute this utility from Casper only'
   exit -1
fi

EXEDIR=$(dirname ${BASH_SOURCE[0]})
args="$*"
unset help
for arg in $args
do
   if test "$arg" = "-h" || test "$arg" = "--help" ; then
      help="help"
      break
   fi
done
if [ ! -z "$help" ] ; then
   ${EXEDIR}/qdh.ssh --help
else
   ssh -t -oHostBasedAuthentication=yes squall.ucar.edu ${EXEDIR}/qdh.ssh $@
fi
